name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy
        shell: cmd
        run: |
          cd /d G:\autoshopbackend\Autoshop
          git fetch origin
          git reset --hard origin/main
          C:\nvm4w\nodejs\npm.cmd install
          C:\nvm4w\nodejs\pm2.cmd restart autoshop-api
